### ISSUE TITLE
Private links

### ISSUE THREAD

**Issue by mika76** [knalli/delicious-exporter#1]
This is great! Does it do private links? If not could you add that functionality?

**Comment by knalli** [comment]
@mika76 What are private links? Where are they?

**Comment by mika76** [comment]
In delicious you can create a private bookmark - they will only appear on the site if you're logged in though.

https://github.com/szafranek/delicious-exporter supports it although it's in ruby so not as cool as your project 😄

**Comment by knalli** [comment]
Ok, so all we need is sending the credentials and maybe evaluating the flag private?

Feel free to contribute :)

**Comment by mika76** [comment]
I might just 😊 ...

**Comment by knalli** [comment]
=> 1.1.0

**Comment by mika76** [comment]
Coooool 👍  😊
